language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7.14
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
addons:
  apt:
    packages:
    - slapd
    - libldap-2.4-2
    - libldap2-dev
before_install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - sed -ie "s#base-4.3.x.cfg#base-$PLONE_VERSION.x.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/pip install -r requirements.txt
  - bin/createcoverage
  - python -m coverage.pickle2json
  - coveralls
