language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
    - openldap
python:
  - 2.7.14
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.2
  fast_finish: true
addons:
  apt:
    packages:
    - libssl-dev
install:
  - mkdir -p openldap
  - virtualenv --clear -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#base-4.3.x.cfg#base-$PLONE_VERSION.x.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/pip install -r requirements.txt
  - bin/createcoverage
  - python -m coverage.pickle2json
  - coveralls
